const excusesBilingue = [
    { fr: "Mon bus est tombé en panne.", en: "My bus broke down." },
    { fr: "Il y avait un accident sur la route.", en: "There was an accident on the road." },
    { fr: "J'ai raté mon train.", en: "I missed my train." },
    { fr: "Il y avait beaucoup de trafic.", en: "There was a lot of traffic." },
    { fr: "Mon vélo a crevé.", en: "My bike had a flat tire." },
    { fr: "Le métro était en retard.", en: "The subway was delayed." },
    { fr: "Mon Uber a annulé au dernier moment.", en: "My Uber canceled at the last minute." },
    { fr: "Mon chauffeur a pris le mauvais itinéraire.", en: "My driver took the wrong route." },
    { fr: "J'ai pris le mauvais bus.", en: "I took the wrong bus." },
    { fr: "Mon GPS m'a complètement perdu.", en: "My GPS totally misled me." },
    { fr: "Je me suis réveillé(e) en retard.", en: "I woke up late." },
    { fr: "Je n'ai pas entendu mon réveil.", en: "I didn't hear my alarm." },
    { fr: "J'ai eu une urgence familiale.", en: "I had a family emergency." },
    { fr: "J'ai perdu mes clés.", en: "I lost my keys." },
    { fr: "Mon chien est tombé malade.", en: "My dog got sick." },
    { fr: "J'ai dû aider un voisin.", en: "I had to help a neighbor." },
    { fr: "Mon enfant ne voulait pas aller à l'école.", en: "My child didn't want to go to school." },
    { fr: "J'ai dû aller chez le médecin en urgence.", en: "I had to go to the doctor unexpectedly." },
    { fr: "J'ai oublié quelque chose à la maison et j'ai dû faire demi-tour.", en: "I forgot something at home and had to turn back." },
    { fr: "J'ai eu une fuite d'eau ce matin.", en: "I had a water leak this morning." },
    { fr: "Il y avait une tempête.", en: "There was a storm." },
    { fr: "Il a neigé beaucoup plus que prévu.", en: "It snowed way more than expected." },
    { fr: "Ma voiture était gelée.", en: "My car was frozen over." },
    { fr: "Le vent a fait tomber des arbres sur la route.", en: "The wind knocked down trees on the road." },
    { fr: "Il pleuvait tellement que je ne voyais rien.", en: "It was raining so hard I couldn't see anything." },
    { fr: "J'ai complètement perdu la notion du temps.", en: "I completely lost track of time." },
    { fr: "Je pensais que le rendez-vous était plus tard.", en: "I thought the meeting was later." },
    { fr: "Je me suis trompé(e) de jour.", en: "I got the day wrong." },
    { fr: "J'ai noté la mauvaise heure.", en: "I wrote down the wrong time." },
    { fr: "J'étais absorbé(e) par autre chose.", en: "I got caught up in something else." },
    { fr: "J'étais en réunion.", en: "I was in a meeting." },
    { fr: "Mon ordinateur ne fonctionnait pas.", en: "My computer wasn't working." },
    { fr: "Mon téléphone est tombé en panne.", en: "My phone died." },
    { fr: "Je n'arrivais pas à me connecter.", en: "I couldn't connect." },
    { fr: "J'ai eu un problème de dernière minute avec un projet.", en: "I had a last-minute issue with a project." },
    { fr: "Mon chat a renversé mon café sur moi.", en: "My cat spilled coffee on me." },
    { fr: "Un oiseau est entré chez moi et je devais le faire sortir.", en: "A bird flew into my house and I had to get it out." },
    { fr: "J'ai été enfermé(e) dehors.", en: "I got locked out." },
    { fr: "Mon voisin m'a bloqué avec sa voiture.", en: "My neighbor blocked me with his car." },
    { fr: "Mon alarme a sonné en mode silencieux.", en: "My alarm went off on silent mode." },
    { fr: "J'ai glissé en sortant de chez moi.", en: "I slipped when leaving my house." },
    { fr: "J'ai dû chercher mon portefeuille partout.", en: "I had to look for my wallet everywhere." },
    { fr: "Je suis resté(e) coincé(e) dans l'ascenseur.", en: "I got stuck in the elevator." },
    { fr: "J'ai eu un problème avec la serrure de ma porte.", en: "I had an issue with my door lock." },
    { fr: "J'ai trouvé un chien perdu et j'ai dû appeler un refuge.", en: "I found a lost dog and had to call a shelter." },
    { fr: "Mon miroir a dit que j'avais besoin de plus de temps ce matin.", en: "My mirror said I needed more time this morning." },
    { fr: "Mon lit ne voulait pas me laisser partir.", en: "My bed didn't want to let me go." },
    { fr: "J'ai rêvé que j'étais déjà ici.", en: "I dreamed I was already here." },
    { fr: "J'ai voyagé dans le futur… mais mal réglé l'heure.", en: "I traveled to the future… but set the time wrong." },
    { fr: "Mon café n'était pas prêt à temps.", en: "My coffee wasn't ready in time." },
    { fr: "Je devais finir un appel important.", en: "I had to finish an important call." },
    { fr: "Je n'ai pas trouvé de place pour me garer.", en: "I couldn't find a parking spot." },
    { fr: "J'ai confondu les adresses.", en: "I mixed up the addresses." },
    { fr: "Mon réveil n'a jamais sonné.", en: "My alarm never went off." },
    { fr: "J'ai dû changer de vêtements à la dernière minute.", en: "I had to change clothes at the last minute." },
    { fr: "Mon enfant a fait une crise juste avant de partir.", en: "My child had a meltdown right before leaving." },
    { fr: "Le portail du parking était bloqué.", en: "The parking gate was stuck." },
    { fr: "Je suis tombé sur un embouteillage imprévu.", en: "I hit an unexpected traffic jam." },
    { fr: "Je me suis endormi dans le train.", en: "I fell asleep on the train." },
    { fr: "Mon animal a vomi sur mes chaussures.", en: "My pet vomited on my shoes." },
    { fr: "Je n'ai pas retrouvé mon téléphone.", en: "I couldn't find my phone." },
    { fr: "J'ai oublié de mettre de l'essence.", en: "I forgot to get gas." },
    { fr: "Mon réveil s'était mis à l'heure PM au lieu d'AM.", en: "My alarm was set to PM instead of AM." },
    { fr: "Je me suis cogné l'orteil et j'ai dû me soigner.", en: "I stubbed my toe and had to treat it." },
    { fr: "J'ai dû aider un ami en détresse.", en: "I had to help a friend in need." },
    { fr: "Mon voisin m'a demandé une aide urgente.", en: "My neighbor asked me for urgent help." },
    { fr: "Je suis tombé dans les escaliers.", en: "I fell down the stairs." },
    { fr: "Mon chat s'est enfui et j'ai dû le chercher.", en: "My cat ran away and I had to find it." },
    { fr: "Mon réveil a été débranché pendant la nuit.", en: "My alarm got unplugged during the night." },
    { fr: "J'ai eu un problème avec mon lave-linge.", en: "I had an issue with my washing machine." },
    { fr: "J'ai dû consoler quelqu'un en pleurs.", en: "I had to comfort someone who was crying." },
    { fr: "Je suis resté coincé dans un embouteillage de poussettes.", en: "I got stuck in a stroller traffic jam." },
    { fr: "Mon poisson rouge ne respirait plus (fausse alerte).", en: "My goldfish stopped breathing (false alarm)." },
    { fr: "Mon pain grillé a brûlé et mis le feu à l'alarme incendie.", en: "My toast burned and set off the fire alarm." },
    { fr: "Un insecte géant m'a attaqué dans ma cuisine.", en: "A giant bug attacked me in my kitchen." },
    { fr: "J'ai confondu aujourd'hui avec un jour férié.", en: "I confused today with a holiday." },
    { fr: "Je voulais juste dormir cinq minutes de plus…", en: "I just wanted five more minutes of sleep…" },
    { fr: "Mon chien a refusé de rentrer.", en: "My dog refused to come back inside." },
    { fr: "J'ai dû repasser ma chemise trois fois.", en: "I had to iron my shirt three times." },
    { fr: "Je suis resté coincé derrière une voiture-école.", en: "I got stuck behind a driving school car." },
    { fr: "J'ai eu une discussion existentielle sous la douche.", en: "I had an existential shower thought." },
    { fr: "Ma cafetière a explosé.", en: "My coffee machine exploded." },
    { fr: "Le facteur m'a bloqué dans l'allée.", en: "The mailman blocked my driveway." },
    { fr: "J'ai glissé sur une feuille mouillée.", en: "I slipped on a wet leaf." },
    { fr: "J'ai pris mon parapluie pour aller dormir dehors…", en: "I took my umbrella and accidentally walked outside in pajamas." },
    { fr: "Je ne trouvais plus ma chaussette porte-bonheur.", en: "I couldn't find my lucky sock." },
    { fr: "Mon voisin faisait un barbecue à 8h du matin. J'ai dû enquêter.", en: "My neighbor was having a barbecue at 8am. I had to investigate." },
    { fr: "J'ai été pris dans une manifestation inattendue.", en: "I got caught in an unexpected protest." },
    { fr: "Ma voiture a décidé de ne pas démarrer par caprice.", en: "My car randomly decided not to start." },
    { fr: "Je me suis coincé(e) dans mes vêtements.", en: "I got stuck in my clothes." },
    { fr: "J'ai oublié que j'avais une réunion aujourd'hui.", en: "I forgot I had a meeting today." },
    { fr: "Je suis tombé dans un trou (littéralement).", en: "I fell into a hole (literally)." },
    { fr: "J'ai eu une crise de panique imprévue.", en: "I had an unexpected panic attack." },
    { fr: "Le réveil a été mangé par le chien.", en: "The dog ate my alarm clock." },
    { fr: "Mon voisin a enclenché sa sirène anti-vol par erreur.", en: "My neighbor accidentally triggered his car alarm." },
    { fr: "J'ai voulu méditer… mais trop longtemps.", en: "I tried to meditate… for too long." },
    { fr: "Mon rideau de douche est tombé sur moi.", en: "My shower curtain fell on me." },
    { fr: "Un groupe de canards bloquait la route.", en: "A group of ducks was blocking the road." },
];
